### ISSUE TITLE
Cant edit shared note

### ISSUE THREAD

**Issue by steve-s-71** [brantje/nextnote#10]
I shared a note with a test user. Test user can read the note and see the shared icon, but neither the edit icon nor the delete icon.

Now when I un-share the note, it becomes wired: Then the note is still visible for the test user and even worse, the test user suddenly see the edit icon and the delete icon. Test user can really edit and save. The modification seems to be stored for the test user, but the note appears unchanged under my login.

**Comment by brantje** [comment]
What branch are you using?

**Comment by steve-s-71** [comment]
Master, downloaded from here: https://github.com/brantje/ownnote

Is that wrong?

**Comment by brantje** [comment]
Well the app is in alpha stage currently, so for sure things won't work.
Please wait till the app reaches stable, as running alpha's could result in loss of notes.
