### ISSUE TITLE
Removing translation resource from Transifex

### ISSUE THREAD

**Issue by rakekniven** [brantje/nextnote#121]
Hello @brantje , 
The app looks deprecated. Am I wrong?

If so I would like to remove the resource from Transifex.

If you ask why? See https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312

Existing translations are not lost. They will remain in this repository.

Please provide feedback.

Thank you

**Comment by rakekniven** [comment]
Hello, 

no response after one month. @brantje Have you seen my issue?

Cheers

**Comment by gary-kim** [comment]
As far as I can tell, @brantje hasn't been active for quite a while

**Comment by rakekniven** [comment]
Ok, I will wait some more days for a response. After it I will disable sync.

**Comment by rakekniven** [comment]
Removed
