### ISSUE TITLE
What should the name of this app be?

### ISSUE THREAD

**Issue by enoch85** [brantje/nextnote#14]
Notes is already taken, and we decided to change name so we need some suggestions.

- NextNotes
- BestNotes
- OpenNotes
- HTMLNotes

Please help us here

**Comment by brantje** [comment]
I like the name OpenNotes

**Comment by enoch85** [comment]
Taken: https://www.opennotes.org/ :(

**Comment by brantje** [comment]
I'll would go with NextNotes in that case

**Comment by enoch85** [comment]
Ok, let's do it.
