### ISSUE TITLE
Editor discussion

### ISSUE THREAD

**Issue by brantje** [brantje/nextnote#15]
So the new API is almost ready, meaning we need a new frontend.
The most important part of the app will be the editor.

So the hunt for the ultimate WYSIWYG editor has started.
Luckily for us, [this has been done before](https://github.com/dandv/comparisons/blob/master/JavaScript-WYSIWYG-editors.md).

My personal requirements:
- Support pasting images from clipboard
- Markdown support would be nice (If not in core then in plugin)
- Good support
- Easy to extend (i want the possibility to import pictures from within Nextcloud)
- Well maintained

So far i like TinyMCE, but the lib is quite big. 
[Trumbowyg](http://alex-d.github.io/Trumbowyg/), looks nice, but maybe too simple for our case? Scratch that, looks good. Good [docs](http://alex-d.github.io/Trumbowyg/documentation.html) too.

**Comment by enoch85** [comment]
Plugins? I think the core functionality should be in core, not some plugin.

In the ownNote app (don't know if you tried, if not please do) it was almost perfect. It looked a bit like word or any other "editor" when there was a top bar with all the choices. Something like [this]( https://www.tinymce.com/), though Trumbowyg would work as well.

So, TinyMCE with pictures is the minimal requirement for me. The stuff like this would be cool as well:
- Smaller videos (just cool, not really needed)
- Export to PDF
- ...

And I agree with everything that you said. Well maintained is the most important part.

**Comment by maestroi** [comment]
I would like to add it must be opensource.
Also Trumbowyg looks very nice i like that it is extendable 👍

**Comment by brantje** [comment]
TinyMCE it is!
