### ISSUE TITLE
Use Transifex for translating

### ISSUE THREAD

**Issue by enoch85** [brantje/nextnote#16]
Also add a scheduled job that automatically fetches the latest translations once a day or similar as in the Nextcloud repo.

**Comment by brantje** [comment]
This will be done one the namespace has been changed to `NextNotes`

**Comment by Fmstrat** [comment]
Would having access to the existing Transifex be helpful?

**Comment by enoch85** [comment]
@MorrisJobke Do you think you could help us with this?

Ref: https://github.com/brantje/nextnote/pull/85#issuecomment-380399425

**Comment by MorrisJobke** [comment]
Fix is in #87 - @nextcloud-bot needs to be admin to be able to push to master.

**Comment by brantje** [comment]
Thank you @MorrisJobke!
