### ISSUE TITLE
Make use of the old Android App until we have developed a new one?

### ISSUE THREAD

**Issue by enoch85** [brantje/nextnote#24]
Why not just fork the old Android app and change the namespace to nextnotes so that users have something to use until we have developed a new Android app? We could release it for free on FDROID or Google Play...

Or maybe that will be double work? Just a suggestion.

The old source is here: https://github.com/Fmstrat/ownnote-mobile

**Comment by e-alfred** [comment]
Releasing it on F-Droid for the time being would be a great option until a new app arrives. Is it still compatible with Nextnote?

**Comment by ThomasDaheim** [comment]
Had a quick look at this. Seems like it has its own note database store and some sophisticated sync mechanism. No wonder, I never managed to get it in sync with the notes I have on my PC...

**Comment by brantje** [comment]
Hi this is, unfortunately not possible since it connects to the /ownnote path. 
For now, i'm closing this issue.
