### ISSUE TITLE
Link under "Files" menu points to index.php/apps/ownnote

### ISSUE THREAD

**Issue by ThomasDaheim** [brantje/nextnote#25]
After uninstalling ownnote and installing & enabling nextnote it shows up under "Admin -> Add. Settings". But when I try to access my notes via the "Files" menu nothing happens.

Link under Files points to "index.php/apps/ownnote" instead of "index.php/apps/nextnote" where I have installed it. Might be an issue that I had ownnote installed previously?

**Comment by brantje** [comment]
Did you disable the old ownnotes app first?

**Comment by ThomasDaheim** [comment]
Yes - at least I think so. In any case after uninstalling nothing should be left from ownnote? Any idea, where that info is stored/determined in nextcloud?

**Comment by brantje** [comment]
Well, i had it too. But i did a ./occ app:disable ownnotes and an enable of nextnotes and it worked.

**Comment by ThomasDaheim** [comment]
I can see various entries from ownnote still in the appconfig table. After deleting them manually the link now points to "index.php/apps/nextnote"!
So we might need to add a few things for user "migrating" from ownnote to nextnote...

**Comment by brantje** [comment]
Unfortunately Nextcloud doesn't have a 'afterInstall' hook. 
This one is gonna be hard

**Comment by brantje** [comment]
Won't be an issue anymore
