### ISSUE TITLE
[FR] Show sidebar when editing

### ISSUE THREAD

**Issue by enoch85** [brantje/nextnote#26]
As discusses on Gitter. Do full screen for now, and implement the sidebar later.

Things to be fixed by then:
1. Save note when pressing something in the sidebar (note/group) https://github.com/brantje/nextnote/issues/22#issuecomment-313870413
2. ...?

**Comment by steve-s-71** [comment]
As further discussed on Gitter, have a settings menu and make „hide/not hide sidebar when editing“ configurable.

**Comment by brantje** [comment]
Closing, since the new view mode solves this problem.
