### ISSUE TITLE
Saved parts too big - storing fails

### ISSUE THREAD

**Issue by ThomasDaheim** [brantje/nextnote#29]
Wehn trying to save a note with an image ~3MB of size I get the following error in the log:

```
"An exception occurred while executing 'INSERT INTO ownnote_parts"
"Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes"
```

Seems like the current parts size (```$maxlength = 2621440; // 5 Megs (2 bytes per character)```) is bigger than the allowed default: "The server's default max_allowed_packet value is 4MB". (https://dev.mysql.com/doc/refman/5.7/en/packet-too-large.html).

After increasing 'max_allowed_packet' it works. But still I think the default for nextnote should be in sync with the default of MySQL...

**Comment by brantje** [comment]
The allowed site of the note field is configured [here](https://github.com/brantje/nextnote/blob/master/lib/Db/NextNoteMapper.php#L33). Can you change it or do you want me to change it?

**Comment by ThomasDaheim** [comment]
Would be nice if you could change it. I would want to focus on the folder support.

**Comment by ThomasDaheim** [comment]
BTW How about that occurrence: https://github.com/brantje/nextnote/blob/master/lib/Utility/Utils.php#L59 Is the same done in two places?

**Comment by brantje** [comment]
Good find! Will adapt the service to make use of the Utils

**Comment by enoch85** [comment]
Welcome back @brantje! :)
