### ISSUE TITLE
Embed nextcloud images as base64

### ISSUE THREAD

**Issue by ThomasDaheim** [brantje/nextnote#31]
I know its probably by design BUT :-)

When inserting an image via "Insert/edit image", it is stored in the note as 
```<p><img src="../../../remote.php/webdav/ThomasKlassentrefffen_20150627_cut.jpg" alt="Description" width="100" height="85" /></p>```

- Unfortunately, that disables offline editing of the note
- If the linked file gets moved/renamed/deleted you end up with an empty frame (sorry, can't upload screenshot...)

**Comment by brantje** [comment]
I can return a full URL, but remering file changes is out of the scope.

**Comment by ThomasDaheim** [comment]
I can understand. Thats why ownnote converted everything to inline base64...

**Comment by brantje** [comment]
Great idea. We could use [this](https://stackoverflow.com/a/22172860) to convert the image to base64.
