### ISSUE TITLE
Reference to \OCP\Util::addScript('nextnote', 'admin');

### ISSUE THREAD

**Issue by ThomasDaheim** [brantje/nextnote#35]
Hi,

in https://github.com/brantje/nextnote/blob/master/templates/admin.php the old admin.js is still referenced. But its not there anymore / not yet again.

Bye,
Thomas

**Comment by enoch85** [comment]
Great find!

**Comment by ThomasDaheim** [comment]
Saw it in the logs... In any case we need something similar for nextnote as well, since we have to save the admin settings once changed.
