### ISSUE TITLE
Feature request : One pane view

### ISSUE THREAD

**Issue by fulljackz** [brantje/nextnote#36]
Hi,

I just gave a try to nextnote app. Good work, rich style and media integration are very interesting features !

What about a style change ? I mean "one pane" view such as Outlook for example : 3 columns views.
We could have : 
- Left column : Note lists (sorted by groups ?)
- Middle column : Note title + one or two lines (preview)
- Right column : Note content in an editable view

Thanks for reading.

**Comment by brantje** [comment]
Great idea. Will be implemented before appstore release.

**Comment by ThomasDaheim** [comment]
Left & right columns sound a bit like OneNote. Groups as tabs on top? Or as hierarchy in the left column.

I would probably use tooltip instead of the middle column - saves screen space :-)

**Comment by brantje** [comment]
I'll make a mockup first on a branch so we can discuss it.
