### ISSUE TITLE
Did this project sadly die?

### ISSUE THREAD

**Issue by enoch85** [brantje/nextnote#39]
Would be a shame. :/

**Comment by olesk75** [comment]
I *really* hope not, as I'm a very happy user!

**Comment by mikshepard** [comment]
I hope not, as well.  This is the most used app in my NextCloud (more than the files).

**Comment by enoch85** [comment]
It all started out so good. A lot of enthusiasm. Then @brantje got other things taken all the time it seems.

**Comment by ThomasDaheim** [comment]
Unfortunately, I don't think my php and angular is good enough to take over :-(

**Comment by brantje** [comment]
Quite busy at work lately, don't even have time to manage my other app (passman).
I hope to get some time around Christmas. 
Also using this myself so.. ye feel you guy's.

**Comment by brantje** [comment]
Oh btw, if anyone likes to work with me on this, just ping me, pull requests are very welcome.

**Comment by ThomasDaheim** [comment]
Maybe on the php end - but my frontend skills are not sufficient :-) I'll (hopefully) have some more free cycles in the next time. Would ping you to see how I could support.

**Comment by ThomasDaheim** [comment]
Out of curiosity: While working my way through the I have found a lot of similarities with the nextcloud tutorial app (https://docs.nextcloud.com/server/9/developer_manual/app/tutorial.html). So did you use this as a staring point or way the tutorial built based on this app?

**Comment by sunjam** [comment]
I just created a feature request for [integrating NextNote into the default Nextcloud Notes app as issue #138.](https://github.com/nextcloud/notes/issues/183)

**Comment by brantje** [comment]
I'll close this issue, since i'm back (again :P)
