### ISSUE TITLE
Bug when I create a new note

### ISSUE THREAD

**Issue by alexisrosano89** [brantje/nextnote#41]
Hello, when I create a note, the text inside it is not saved.

But if I modify that note, the text inside is correctly saved.

Could you reproduce that?

Regards!

**Comment by ThomasDaheim** [comment]
Yes, I have seen that as well - only haven't opened a bug for it yet. I was surprised that @brantje didn't run into that himself.

**Comment by alexisrosano89** [comment]
Thanks for confirm that bug.

Do you have a workarround for this? I'm looking at the code right now.

**Comment by ThomasDaheim** [comment]
Unfortunately, my angular knowledge is quite limited. I'm looking at NoteEditCtrl.js that seems to do the save ($scope.saveNote) but I would need to try and debug that to understand it. Especially, what would be different for update vs create...

**Comment by alexisrosano89** [comment]
Yeap, im looking at that code too.. And my situation with angular is the same as you :-1:

**Comment by ThomasDaheim** [comment]
So maybe we're able to find something by simply poking around :-)

**Comment by ThomasDaheim** [comment]
Live debugging... Difference I could find so far in the client:

create: NoteFactory.js calls backend with method: 'POST'
update: NoteFactory.js calls backend with method: 'PUT'

**Comment by alexisrosano89** [comment]
Yeap, I've seen that.

The strange thing is that the title and group it's saved correctly with the POST.

**Comment by ThomasDaheim** [comment]
I have some debug output on the server directly in nextnoteapicontroller.php. There already no content is received in the create() method. So its either not sent or not properly declared on the server side.

Update: The POST request from the client contains the content. So its a server issue

**Comment by alexisrosano89** [comment]
Yes, I think that is in client side.

**Comment by alexisrosano89** [comment]
Look at the console, the content is sent!

![screenshot from 2017-11-13 18-11-03](https://user-images.githubusercontent.com/4732738/32749495-4b4623be-c89e-11e7-8892-44fe57281b2d.png)

**Comment by ThomasDaheim** [comment]
Yes, and I think I have found the bug @server side. Need to play around a bit...

**Comment by alexisrosano89** [comment]
Waiting for your comments :call_me_hand:

**Comment by ThomasDaheim** [comment]
OK, seems like nextcloud is doing the matching from the POST parameters to the create() function parameters by NAME

And guess what, in nextnoteapicontroller.php the parameter is called $note instead of $content :-)

Since I'm working on another branch: could you please try to change nextnoteapicontroller.php on your end to replace $note with $content in the create() method? I found two places:

1) in parameter list
2) 'note' => $note

If that fixes it on your end I would change the master branch directly.

**Comment by alexisrosano89** [comment]
Now it's working! :call_me_hand:

**Comment by ThomasDaheim** [comment]
Pull request merged
