### ISSUE TITLE
Echo not working

### ISSUE THREAD

**Issue by alexisrosano89** [brantje/nextnote#44]
Hello!

I'm doing an `echo ......` in nextnoteapicontroller (because in this side i'm creating a pdf in a string), but I can't see that in the screen.

What I have to do??

Regards!

**Comment by ThomasDaheim** [comment]
I don't think it works like that... Return fro the server is whatever is returned in NextNoteMapper (mainly a note object or a list of them). You would probably add a new object to the return value and extract it on the client side - otherwise you would need to extend the note object itself.

**Comment by alexisrosano89** [comment]
Okey, I understand!

Thank you!

**Comment by brantje** [comment]
You can use 
```
echo "string";
exit;
```
