### ISSUE TITLE
Stop-gap Enhancement: Implement API calls for existing ownNote app

### ISSUE THREAD

**Issue by Fmstrat** [brantje/nextnote#46]
I'm really happy this was forked off, but since this project has slowed down since inception, I would recommend the next element developed be to implement API calls that match up with the existing Android App. See https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php and https://github.com/Fmstrat/ownnote/blob/master/appinfo/routes.php for reference.

Personally, I've been continuing to use ownNote because of this as I was waiting for the new app to fire up.

Thoughts?

**Comment by ThomasDaheim** [comment]
A working Android app would be a fine thing indeed! Since I'm practically not using the owncloud/nextcloud webfrontend anyways I could live with any backend implementation...

**Comment by enoch85** [comment]
Any type of progress with this app would be welcome!

**Comment by e-alfred** [comment]
Using the existing Android app (which is Open Source for some time now, thanks @Fmstrat ) would be a good alternative and remove an important checkmark point after all.

As the Android app is based on Cordova, it might be possible to port it to iOS too.

**Comment by Fmstrat** [comment]
@e-alfred I had tried to port to iOS, but the browser implementation was terrible for WYSIWYG support (I am the author of ownNote, btw). I think this was the basis for creating a new app by the Nextcloud team that used different plugins. Unfortunately despite a big quick push, interest seems to have slowed, and I don't have the bandwidth to keep things moving on the base code, either. :(

**Comment by enoch85** [comment]
> Unfortunately despite a big quick push, interest seems to have slowed,

Just want to be clear that the interest is still the same. It's rather lack of time that affects this repo I'm afraid. :/

**Comment by e-alfred** [comment]
For the time being I patched up Ownnote to make it work with Nextcloud 13+:

https://github.com/e-alfred/ownnote

**Comment by Fmstrat** [comment]
@e-alfred Why not send a PR? I'd pull it into ownNote. I usually update to support Nextcloud anyway as that's what I use, just haven't updated to 13 yet ;)

**Comment by brantje** [comment]
As far i can see in the code NextNote already offers an API:

![image](https://user-images.githubusercontent.com/2758767/38267122-d620d45c-377a-11e8-8b02-f839b0ce98c1.png)

**Comment by Fmstrat** [comment]
@brantje In another ticket I thought someone had mentioned the APIs for mobile were pulled, and only the ones for the ajax calls were there?

**Comment by brantje** [comment]
Afaik not, i completely redid the api, following REST standards.

**Comment by Fmstrat** [comment]
That's what I thought, thanks.

**Comment by e-alfred** [comment]
Maybe integration with Joplin (https://github.com/laurent22/joplin/issues/228) would be a better idea to solve the problem of missing desktop (Windows/Linux/Macos) and mobile (Android/iOS) apps.

**Comment by brantje** [comment]
Well the thing is, Joplin uses markdown, while nextnote uses html. That won't work, unless Joplin implements it.
