### ISSUE TITLE
activation problem with nextcloud 13.0.1

### ISSUE THREAD

**Issue by tdanel94** [brantje/nextnote#48]
Hi,
after upgrading nextcloud 13.0.0 to 13.0.1, nextnote can't be activate

"occ app:enable nextnote"  return no error

"occ app:check-code nextnote" return a lot of error and return "APP is not conpliant"

Have you planned to work the code ?

Best regards
Thierry

**Comment by enoch85** [comment]
cc @brantje

**Comment by Leorivasc** [comment]
Hi, 
Had the same problem.
Fixed using the pull request modification here:
https://github.com/brantje/nextnote/pull/47/commits/dcfc7619ff658ff1673c328da8a4daae11f92332

Cheers.

**Comment by tdanel94** [comment]
Thanks, 
It's working again ;)

Best Regards
Thierry

**Comment by enoch85** [comment]
Please close this since iit's solved.
