### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by billbillsen** [brantje/nextnote#57]
I have a display error when i update today's version too. (from version 1.1 to version 1.2 says the app store)
![grafik](https://user-images.githubusercontent.com/18520024/38327135-c3a4f344-3847-11e8-8d7e-26acd80816b7.png)

NC Version 12.0.6
The NC log:
`Declaration of OCA\NextNote\Fixtures\ShareFix::getUsersItemShared() should be compatible with OC\Share\Share::getUsersItemShared($itemType, $itemSource, $uidOwner, $includeCollections = false, $checkExpireDate = true) at /xxxxxxx/apps/nextnote/lib/Fixtures/ShareFix.php#0`

Any idea?

**Comment by brantje** [comment]
Can you try clearing the browser cache?

**Comment by billbillsen** [comment]
I cleared the cache, but no change. I have installed version 1.1 again and will test the master branch again on the weekend.

**Comment by billbillsen** [comment]
**Software Version**
Browser: Firefox 59.0.2
Nextcloud: 12.0.6
Nextnote app: Upgrade from 1.1 to 1.2.1

**Steps to reproduce**
1. Disable Vers. 1.1
2. Remove Vers 1.1
3. Download current branch, set file permissions ....
4. Enable Vers. 1.2.1
    Nextcloud want to upgrade the app but nothing happens. Only the app page is reloaded.
![grafik](https://user-images.githubusercontent.com/18520024/38453368-e99989d4-3a54-11e8-8522-555d7aa05663.png)
5. Showing notes. No notes are displayed..... (cleared the cache, restart the browser no effect)
6. App integrity check executed from command line
```
$ php occ integrity:check-app nextnote
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Signature data not found.
```
7. Executed from command line `php occ maintenance:repair` 
8. The notes are there! ... but the same display as above

**And the Log**
`Error	PHP	Declaration of OCA\NextNote\Fixtures\ShareFix::getUsersItemShared() should be compatible with OC\Share\Share::getUsersItemShared($itemType, $itemSource, $uidOwner, $includeCollections = false, $checkExpireDate = true) at xxxxx/apps/nextnote/lib/Fixtures/ShareFix.php#0	2018-04-07T10:58:44+0200

Error	PHP	Undefined variable: undefinedVariable at xxxxx/3rdparty/nikic/php-parser/lib/PhpParser/Lexer.php#70	2018-04-07T10:54:33+0200

Error	PHP	Undefined variable: undefinedVariable at xxxxx/3rdparty/nikic/php-parser/lib/PhpParser/Lexer.php#70	2018-04-07T10:45:49+0200

Error	PHP	file_get_contents(xxxxx/apps/nextnote/appinfo/signature.json): failed to open stream: No such file or directory at xxxxx/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#39	2018-04-07T10:43:22+0200

Error	PHP	Undefined variable: undefinedVariable at xxxxx/3rdparty/nikic/php-parser/lib/PhpParser/Lexer.php#70	2018-04-07T10:39:31+0200

Error	PHP	Undefined variable: undefinedVariable at xxxxx/3rdparty/nikic/php-parser/lib/PhpParser/Lexer.php#70	2018-04-07T10:39:31+0200`

**Comment by brantje** [comment]
Goodmorning.
Step 6 doesn't make sense because the app isn't even out yet.
Display error will be fixed once i finish the ThreePaneView =)

**Comment by billbillsen** [comment]
Okay, I was just noticing.....

I have fixed the error as follows:
Editing the css file -> xxxx/apps/nextnote/js/vendor/tinymce/skins/lightgray/skin.min.css
and changed line 75 from
```
.mce-tinymce {
    display: block;
}
```
too
```
.mce-tinymce {
    display: block;
    margin-top:44px;
}
```
(I'm not sure this is the best solution, but it works.)

I will wait for the ThreePaneView to be finished :)
