### ISSUE TITLE
Feature Request - Example Note on new installations ala "Welcome to NextNote"

### ISSUE THREAD

**Issue by sunjam** [brantje/nextnote#78]
New installations could include a rich text or html example note that includes:
- A helpful list of available Keyboard Shortcuts under the Help / ? Menu and a link to the project Github page and Telegram group.
- Perhaps some animated GIF files or screenshots #71 with examples of how to use NextNote to share, embed media, etc.
![nexnote-drag-and-drop-example-bigger](https://user-images.githubusercontent.com/1787238/38581663-58ecc3b8-3cc2-11e8-9011-970ace95a5f5.gif)

**Comment by brantje** [comment]
@nickvergessen Any idea how we can implement this? I was thinking about a user variable. If that is not set, then insert the example note

**Comment by nickvergessen** [comment]
"Copy" the first run wizard app?

**Comment by brantje** [comment]
This is in master since 4733eb6fd456dc5115c674bb60530464b32d9d8f @sunjam do you want to make the example note?
