### ISSUE TITLE
Implement IQueryBuilder

### ISSUE THREAD

**Issue by brantje** [brantje/nextnote#83]
No idea how to do this, yet. We have [docs](https://docs.nextcloud.com/server/14/developer_manual/api/OCP/DB/QueryBuilder/IQueryBuilder.html) but that just describes the methods.

Aim of this is better compatibility between different databases.

Pinging @MorrisJobke @icewind1991 @MorrisJobke @nickvergessen @jancborchardt
How do i implement this in my app? Is there any example?
Best would be a PR which modifies 1 entity, eg note for example.
However i understand that, if you're busy that's not an option.

**Comment by nickvergessen** [comment]
I will do it

**Comment by nickvergessen** [comment]
> ERROR: Permission to brantje/nextnote.git denied to nickvergessen.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Mind to add me?

**Comment by brantje** [comment]
Yes, one second

**Comment by brantje** [comment]
Done, you can join us by visiting [this](https://github.com/brantje/nextnote/invitations) link =).

**Comment by brantje** [comment]
@nickvergessen How can i do a `COUNT()`? It's used [here](https://github.com/brantje/nextnote/blob/master/lib/Db/NotebookMapper.php#L67).
Fixed. Final code:
```
	$this->qb->select('g.*', 'g.guid as guid', $this->qb->createFunction('COUNT(n.id) as note_count')) //'COUNT(n.id) as note_count'
			->from('nextnote_groups', 'g')
			->leftJoin('g','nextnote_notes','n',  $this->qb->expr()->eq('g.id', 'n.notebook'))->groupBy(['g.id']);
```

**Comment by brantje** [comment]
Fixed with 2749443f87146981d9939acd11945762b8146625

**Comment by nickvergessen** [comment]
Instead of `as` please use `selectAlias()`

**Comment by brantje** [comment]
So it becomes `$this->qb->createFunction('COUNT(n.id)')->selectAlias('note_count')`?

**Comment by nickvergessen** [comment]
Actually
`$this->qb->selectAlias($this->qb->createFunction('COUNT(' . $this->qb->getColumnName('n.id') . ')'), 'note_count')`

Ps typed on phone, so no guarantee for typos

**Comment by brantje** [comment]
Perfect that works. Thanks.
