### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by brantje** [brantje/nextnote#9]
Post your wishlist here and i'll see what i / we can do :+1: 
- Database backend, with ability to import / export from / to files
- Folder based structure for managing notes

**Comment by enoch85** [comment]
- Import / export function (txt, html at least + .MD maybe?)
- Android App (ofc) 
- Widget for the Android app

**Comment by steve-s-71** [comment]
As I am not a programmer, I try to provide some contribution by offering ideas:

- A proper Android App should be IMHO one of the top priorities
- Notebooks, as additional hierarchy above groups. Like in MS One Note.
- A Desktop App with offline function and sync via the regular NC Desktop Sync app (faster usage than Browser based). Eventually here is an option to cover Linux/Win/Mac with one effort - and eventually even cover the Android App (Android=Linux): https://github.com/electron/electron
- Store what group was selected and recall that when entering the app/note-website next time.
- Search function (titles and content). Maybe certain reuse of Nexant is possible for this. 
- Replace “Save” and “Fast Save” by an automatic save function
- Check-Box feature like in Google Notes (usecases: shopping list, task list, etc) 
- Real time Spell checker.

**Comment by ThomasDaheim** [comment]
@steve-s-71 👍 
- Desktop App: you might want to give https://github.com/ThomasDaheim/ownNoteEditor a try :-) Since its JavafX it can in theory also be extended to Android...
- Check-Box: tricky in html to store checked/unchecked
- Hierarchie of groups: can be done, bit tricky with the more complex UI

As for my wishes (will try and move my changes to her to create pull requests for both...)
- prism,js support (for automatic highlighting)
- folder only mode

**Comment by e-alfred** [comment]
Is an integration with Deck (https://github.com/nextcloud/deck) possible? Linking Kanban stacks/items to notes would definitely be a good feature. Also it would integrate well with yet another app too.

**Comment by ThomasDaheim** [comment]
Hi @e-alfred , a quick look on Deck indicates, that markdown is used there. That fits a lot better to the https://github.com/nextcloud/notes app?

**Comment by e-alfred** [comment]
@ThomasDaheim Yes, markdown is supported, so probably better suited with the Notes app.

**Comment by alexisrosano89** [comment]
Change the font of the text in the note may be it's a good enhancement.

**Comment by sunjam** [comment]
> Change the font of the text in the note may be it's a good enhancement.

I believe this is currently possible from the editor.  I was able to change font in current release.

> ...markdown is used there. That fits a lot better to the https://github.com/nextcloud/notes app?

@ThomasDaheim @e-alfred perhaps NextNote Notes could also be attached to Deck cards once the our API (and [their CalDAV](https://github.com/nextcloud/deck/issues/15) + [Rest API](https://github.com/nextcloud/deck/issues/83)) is solidified.

- Add unsupported formats or large files directly to Nextcloud Files app in the background via WebDAV, with a link embedded into Note.
- [Nextcloud OCR - Ocular Character Recognition support](https://github.com/janis91/ocr)
- [Full Text Elastic Search support](https://github.com/nextcloud/fulltextsearch_elasticsearch)
- [Index searched files into NextNote](https://github.com/nextcloud/files_fulltextsearch)
- [Nextcloud Audio Player integration](https://apps.nextcloud.com/apps/audioplayer)
- [Nextcloud Movie Player integration](https://github.com/nextcloud/files_videoplayer)
- [Nextcloud Reader Integration](https://github.com/Yetangitu/owncloud-apps) for embedding PDF, CBR, CBZ, etc.
- [PDFViewer Integration](https://github.com/nextcloud/files_pdfviewer)
- [Nextcloud Draw.io Integration](https://github.com/pawelrojek/nextcloud-drawio)
- [Nextcloud Polls Integration](https://github.com/nextcloud/polls)
- [Nextcloud Contacts / CarDAV Integration for sharing](https://github.com/nextcloud/contacts)
- [Circles app support for federated shared notes.](https://github.com/nextcloud/circles/wiki)
- [Attach NextNote Note to a Circle.](https://github.com/nextcloud/circles/issues/142)  Currently a basic description is supported.
- Automatically add my own fonts, otf or ttf, ideally from a specific folder within Nextcloud
- Integrate NextNote Notes with [Nextcloud Calendar](https://github.com/nextcloud/calendar
) events.  Who doesn't want some notes to go with a Calendar event...
- Attach [NextNote Notes to Nextcloud Bookmarks entries.](https://github.com/nextcloud/bookmarks/issues/447)
- Add urls from NextNote to [Nextcloud Bookmarks](https://github.com/nextcloud/bookmarks).
- Import urls from [Nextcloud Bookmarks](https://github.com/nextcloud/bookmarks) to NextNote, perhaps once [they implement a Share API](https://github.com/nextcloud/bookmarks/issues/5)
- [Save/sync/import offline bookmarks from Shiori/Bookmarks app to NextNote](https://github.com/nextcloud/bookmarks/issues/438)
- [Integrate Mindmaps app with NextNote api](https://github.com/splitt3r/mindmaps/issues/52).
- [Email directly to NextNote from Files_tomail app](https://github.com/nextcloud/files_frommail/issues/10)
- [Activity app support for NextNote Notes](https://github.com/nextcloud/activity)
- [Share NextNote Notes to Talk application](https://github.com/nextcloud/spreed/)
- [Save Nextcloud Talk sessions/text chats/calls to NextNote](https://github.com/nextcloud/spreed/)
- Save [Nextcloud Mail](https://github.com/nextcloud/mail) and [Rainloop app](https://github.com/pierre-alain-b/rainloop-nextcloud) emails to NextNote
- [Host notes as html via public url on PicoCMS app](https://github.com/nextcloud/cms_pico)
- Add [comments support on notes being shared with other users](https://github.com/nextcloud/server/issues/7315)
- Use NextNote to host templates for Mail and Rainloop.
- Select and merge multiple notes.
- Select multiple notes and create a table of contents note.
- embed markdown output with a note + hyperlink to md file

**Comment by sunjam** [comment]
- [It would be nice if you could export to the Nextcloud filesytem as different file types](https://github.com/brantje/nextnote/issues/96) such as odt, docx, html or text (md?)
- [Web clipper support](https://github.com/brantje/nextnote/issues/99), possibly through *[Save Page WE](https://addons.mozilla.org/en-US/firefox/addon/save-page-we/)* or *[Tagspaces web clipper](https://github.com/tagspaces/browser-extensions)* extensions for Firefox and Chrome

**Comment by ludodo** [comment]
Great job first.
I agree with the need of : 
- search tool to find text into the numerous notes,
- text/html export.
